name: practical_pachprthlo
description: "A project empowered by pagination, charts, provider, themes, and internalization using BLoC"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  # Dio
  dio: ^5.4.3+1

  # Bloc and Provider
  flutter_bloc: ^8.1.6
  provider: ^6.1.2
  equatable: ^2.0.5

  # Network Image
  cached_network_image: ^3.3.1

  # Dropdown
  dropdown_search: ^5.0.6

  # Charts
  fl_chart: ^0.68.0

  # Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  connectivity_plus: ^6.0.3
  get_it: ^7.7.0

  # Key value DB
  shared_preferences: ^2.2.3

  # Internalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  photo_view: ^0.15.0
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # To build files
  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.6.0

# For internalization
flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
